### ISSUE TITLE
Document Search

### ISSUE THREAD

**Issue by j2whiting** [DARPA-ASKEM/GoLLM#10]
**Goal**

Perform semantic search over documents 

**Tasks**

- [x] figure out schema with @dgauldie & @kbirk
- [ ] bulk ingest docs into ES
- [ ] embedding service for user queries  
- [ ] connect to semantic search UI
- [ ] build summarization service to summarize search results

Note: I have already built the vector index for this and have shared with the team offline.

**Comment by j2whiting** [comment]
@j2whiting to build an embedding task for embedding user queries by EoD
