### ISSUE TITLE
Model Search

### ISSUE THREAD

**Issue by j2whiting** [DARPA-ASKEM/GoLLM#9]
Depends on https://github.com/DARPA-ASKEM/data-service/issues/363

**Goal**

Build out the tasks and data required for semantic search across AMRs 

**Tasks**

- [x] build model card task
- [ ] Scrape models from bio models, convert to amr, fetch associated papers 
- [ ] Create model cards for each model from associated paper
- [ ] Create embedding task within GoLLM
- [ ] Create embedding for each model card 
- [ ] Upload amr, paper DOI, model card and model card embedding to ES
- [ ] Configure facet in HMI server. User query gets sent to embedding task, then an ANN search is performed against the model card embeddings. Top K models are returned to the user. 

**Misc**

- Add model created date to model card

**Comment by j2whiting** [comment]
@liunelson fetching the missing papers isn't as straight forward as it seemed initially. I've filtered them down to a collection of ~1000 open access papers. Fetching the PDF from google scholar using the DOI seems like the best way to grab these. I'm building an ad hoc scraper for this now
